name: Moodle Plugin CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04

    services:
      mariadb:
        image: mariadb:10.6
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u root"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 3

    strategy:
      fail-fast: false
      matrix:
        include:
          - php: '8.1'
            moodle-branch: 'MOODLE_404_STABLE'
            database: mysqli
          - php: '8.2'
            moodle-branch: 'MOODLE_405_STABLE'
            database: mysqli

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          path: plugin

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl, xml, curl, zip, gd, mysqli
          ini-values: max_input_vars=5000
          coverage: none

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Initialise moodle-plugin-ci
        run: |
          composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^4
          echo "$(cd ci/bin && pwd)" >> $GITHUB_PATH
          echo "$(cd ci/vendor/bin && pwd)" >> $GITHUB_PATH

      - name: Install Moodle
        run: moodle-plugin-ci install --plugin ./plugin --db-host=127.0.0.1
        env:
          DB: ${{ matrix.database }}
          MOODLE_BRANCH: ${{ matrix.moodle-branch }}

      - name: PHP Lint
        run: moodle-plugin-ci phplint

      - name: PHP Mess Detector
        continue-on-error: true
        run: moodle-plugin-ci phpmd

      #  FIXED:
      - name: Moodle Code Checker
        run: moodle-plugin-ci phpcs --max-warnings 0 --exclude local_examnotice/amd/build

      #  relaxed
      - name: Moodle PHPDoc Checker
        continue-on-error: true
        run: moodle-plugin-ci phpdoc

      - name: Validate
        run: moodle-plugin-ci validate

      - name: Check upgrade savepoints
        run: moodle-plugin-ci savepoints

      - name: Mustache Lint
        run: moodle-plugin-ci mustache

      - name: Grunt (AMD build)
        run: moodle-plugin-ci grunt

      - name: PHPUnit tests
        continue-on-error: true
        run: moodle-plugin-ci phpunit

      - name: Mark cancelled jobs as failed
        if: ${{ cancelled() }}
        run: exit 1